name: reusable_linting_pure_python

on:
  workflow_dispatch:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      linting_folder:
        description: "Location of the python folder to be linted"
        required: true
        type: string
  workflow_call:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      linting_folder:
        description: "Location of the python folder to be linted"
        required: true
        type: string

jobs:
  check_python_linting:
    name: check_python_linting
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          pip install ${{ inputs.python_folder }}/[dev]
      - name: Check - ruff
        run: |
          cd ${{ inputs.python_folder }}/
          ruff check ${{ inputs.linting_folder }}
      - name: Check - mypy
        run: |
          cd ${{ inputs.python_folder }}/
          mypy ${{ inputs.linting_folder }}
      - name: Check - black
        run: |
          cd ${{ inputs.python_folder }}/
          black --check ${{ inputs.linting_folder }}
