name: reusable_publish_documentation_pure_python_sphinx

on:
  workflow_dispatch:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      docs_folder:
        description: "Location of the sphinx doc folder"
        required: true
        type: string
  workflow_call:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      docs_folder:
        description: "Location of the sphinx doc folder"
        required: true
        type: string

jobs:
  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ${{ inputs.python_folder }}/[docs]
    - name: Build Documentation
      run: |
        cd ${{ inputs.docs_folder }}
        python -m sphinx -T -E -b html . _build/html
        cd ../../
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ inputs.docs_folder }}/_build/html/
