name: reusable_tests_pure_python

on:
  workflow_dispatch:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      test_code_coverage:
        description: "Whether or not to check the coverage when running pytest"
        required: true
        type: boolean
      windows:
        description: "Run unittests on windows"
        required: false
        default: false
        type: boolean
      macos:
        description: "Run unittests on macOS"
        required: false
        default: true
        type: boolean
      python_3_14:
        description: "Run unittest on Python 3.14"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      test_code_coverage:
        description: "Whether or not to check the coverage when running pytest"
        required: true
        type: boolean
      windows:
        description: "Run unittests on windows"
        required: false
        default: false
        type: boolean
      macos:
        description: "Run unittests on macOS"
        required: false
        default: true
        type: boolean
      python_3_14:
        description: "Run unittest on Python 3.14"
        required: false
        default: false
        type: boolean

jobs:
  test_python_linux:
    name: test_python_linux-${{ matrix.python.interpreter }}
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python: [
            { py: "3.10", interpreter: "python3.10" },
            { py: "3.11", interpreter: "python3.11" },
            { py: '3.12', interpreter: "python3.12" },
            { py: '3.13', interpreter: "python3.13" },
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.py }}
      - name: Install dependencies
        run: pip install ${{ inputs.python_folder }}/[tests]
      - name: Test with Coverage pytest
        if: ${{ inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/ --cov=${{ inputs.python_folder }} --cov-fail-under=80
      - name: Test without Coverage pytest
        if: ${{ !inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/

  test_python_linux_py314:
    name: test_python_linux_python3.14
    if: ${{ inputs.python_3_14 }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          pip install setuptools
          pip install ${{ inputs.python_folder }}/[tests]
      - name: Test with Coverage pytest
        if: ${{ inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/ --cov=${{ inputs.python_folder }} --cov-fail-under=80
      - name: Test without Coverage pytest
        if: ${{ !inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/

  test_python_windows:
    if: ${{ inputs.windows }}
    name: test_python_windows_${{ matrix.python.interpreter }}
    runs-on: "windows-latest"
    strategy:
      matrix:
        python: [
            { py: "3.10", interpreter: "python3.10" },
            { py: "3.11", interpreter: "python3.11" },
            { py: '3.12', interpreter: "python3.12" },
            { py: '3.13', interpreter: "python3.13" },
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.py }}
      - name: Install dependencies
        run: pip install ${{ inputs.python_folder }}/[tests]
      - name: Test with Coverage pytest
        if: ${{ inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/ --cov=${{ inputs.python_folder }} --cov-fail-under=80
      - name: Test without Coverage pytest
        if: ${{ !inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/

  test_python_windows_py314:
    if: ${{ inputs.windows && inputs.python_3_14 }}
    name: test_python_windows_python3.14
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          pip install setuptools
          pip install ${{ inputs.python_folder }}/[tests]
      - name: Test with Coverage pytest
        if: ${{ inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/ --cov=${{ inputs.python_folder }} --cov-fail-under=80
      - name: Test without Coverage pytest
        if: ${{ !inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/

  test_python_macos:
    if: ${{ inputs.macos }}
    name: test_python_macos_${{ matrix.python.interpreter }}
    runs-on: "macOS-15"
    strategy:
      matrix:
        python: [
            { py: "3.10", interpreter: "python3.10" },
            { py: "3.11", interpreter: "python3.11" },
            { py: '3.12', interpreter: "python3.12" },
            { py: '3.13', interpreter: "python3.13" },
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.py }}
      - name: Install dependencies
        run: pip install ${{ inputs.python_folder }}/[tests]
      - name: Test with Coverage pytest
        if: ${{ inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/ --cov=${{ inputs.python_folder }} --cov-fail-under=80
      - name: Test without Coverage pytest
        if: ${{ !inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/
  
  test_python_macos_py3_14:
    if: ${{ inputs.macos && inputs.python_3_14 }}
    name: test_python_macos_python3.14
    runs-on: "macOS-15"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          pip install setuptools
          pip install ${{ inputs.python_folder }}/[tests]
      - name: Test with Coverage pytest
        if: ${{ inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/ --cov=${{ inputs.python_folder }} --cov-fail-under=80
      - name: Test without Coverage pytest
        if: ${{ !inputs.test_code_coverage }}
        run: |
          cd ${{ inputs.python_folder }}
          pytest tests/
