name: reusable_linting_rust_pyo3

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy -- -D warnings

  cargo_deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        log-level: warn
        command: check
        arguments: --all-features
        command-arguments: ""
