name: reusable_publish_documentation_rust_sphinx

on:
  workflow_dispatch:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      py_docs_folder:
        description: "Location of the sphinx doc folder"
        required: true
        type: string
  workflow_call:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      py_docs_folder:
        description: "Location of the sphinx doc folder"
        required: true
        type: string

jobs:
  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ${{ inputs.py_interface_folder }}/[docs]
    - name: Build Documentation
      run: |
        cd ${{ inputs.py_docs_folder }}
        python -m sphinx -T -E -b html . _build/html
        cd ../../
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ inputs.py_docs_folder }}/_build/html/
