name: reusable_linting_pure_python

on:
  workflow_dispatch:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      linting_folder:
        description: "Location of the python folder to be linted"
        required: true
        type: string
      windows:
        description: "Run unittests on windows"
        required: false
        default: false
        type: boolean
      macos:
        description: "Run unittests on macOS"
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      python_folder:
        description: "Location of the python folder"
        required: true
        type: string
      linting_folder:
        description: "Location of the python folder to be linted"
        required: true
        type: string
      windows:
        description: "Run unittests on windows"
        required: false
        default: false
        type: boolean
      macos:
        description: "Run unittests on macOS"
        required: false
        default: true
        type: boolean

jobs:

  test_python_linting_linux:
    name: python_check_linting_linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov flake8 flake8-bugbear flake8-docstrings flake8-annotations darglint mypy qoqo
          pip install ${{inputs.python_folder}}/
      - name: Lint with flake8
        run: |
          flake8 --config=${{inputs.python_folder}}/.flake8 ${{inputs.linting_folder}} --count
      - name: Mypy check
        run: |
          mypy --config-file=${{inputs.python_folder}}/.mypy.ini ${{inputs.linting_folder}}


  test_python_linting_windows:
    name: python_check_linting_windows
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.0.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
        python-version: "3.9"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov flake8 flake8-bugbear flake8-docstrings flake8-annotations darglint mypy qoqo
          pip install ${{inputs.py_interface_folder}}/
      - name: Lint with flake8
        run: |
          flake8 --config=${{inputs.python_folder}}/.flake8 ${{inputs.linting_folder}} --count
      - name: Mypy check
        run: |
          mypy --config-file=${{inputs.python_folder}}/.mypy.ini ${{inputs.linting_folder}}
