name: reusable_build_pure_python

on:
  workflow_dispatch:
    inputs:
      python_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
  workflow_call:
    inputs:
      python_folder:
        description: "Location of the py interface folder"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd ${{ inputs.python_folder }}
        python -m build
        twine upload --skip-existing dist/*
